"""Add stores, services, and appointments tables

Revision ID: e2286eeaf919
Revises: 
Create Date: 2026-01-03 20:11:52.848156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2286eeaf919'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_images_id'), 'store_images', ['id'], unique=False)
    op.create_index(op.f('ix_store_images_store_id'), 'store_images', ['store_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opening_hours', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_city'), 'stores', ['city'], unique=False)
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_id'), 'verification_codes', ['id'], unique=False)
    op.create_index(op.f('ix_verification_codes_phone'), 'verification_codes', ['phone'], unique=False)
    op.drop_table('salons')
    op.drop_table('stylists')
    op.drop_index('id', table_name='__drizzle_migrations')
    op.drop_table('__drizzle_migrations')
    op.drop_index('users_openId_unique', table_name='users')
    op.drop_table('users')
    op.drop_table('reviews')
    op.drop_table('favorites')
    op.add_column('appointments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('store_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('service_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('appointment_date', sa.Date(), nullable=False))
    op.add_column('appointments', sa.Column('appointment_time', sa.Time(), nullable=False))
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_service_id'), 'appointments', ['service_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_store_id'), 'appointments', ['store_id'], unique=False)
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    op.drop_column('appointments', 'createdAt')
    op.drop_column('appointments', 'cancellationReason')
    op.drop_column('appointments', 'appointmentDate')
    op.drop_column('appointments', 'userId')
    op.drop_column('appointments', 'serviceId')
    op.drop_column('appointments', 'stylistId')
    op.drop_column('appointments', 'updatedAt')
    op.drop_column('appointments', 'salonId')
    op.add_column('backend_users', sa.Column('phone_verified', sa.Boolean(), nullable=False))
    op.alter_column('backend_users', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('backend_users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_backend_users_email', table_name='backend_users')
    op.create_index(op.f('ix_backend_users_phone'), 'backend_users', ['phone'], unique=True)
    op.add_column('services', sa.Column('store_id', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('services', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('services', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('services', 'category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_store_id'), 'services', ['store_id'], unique=False)
    op.drop_column('services', 'createdAt')
    op.drop_column('services', 'image')
    op.drop_column('services', 'isActive')
    op.drop_column('services', 'duration')
    op.drop_column('services', 'updatedAt')
    op.drop_column('services', 'salonId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('salonId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('updatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('services', sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('isActive', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('image', mysql.TEXT(), nullable=True))
    op.add_column('services', sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_index(op.f('ix_services_store_id'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.alter_column('services', 'category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('services', 'price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('services', 'updated_at')
    op.drop_column('services', 'created_at')
    op.drop_column('services', 'is_active')
    op.drop_column('services', 'duration_minutes')
    op.drop_column('services', 'store_id')
    op.drop_index(op.f('ix_backend_users_phone'), table_name='backend_users')
    op.create_index('ix_backend_users_email', 'backend_users', ['email'], unique=True)
    op.alter_column('backend_users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('backend_users', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('backend_users', 'phone_verified')
    op.add_column('appointments', sa.Column('salonId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('updatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('appointments', sa.Column('stylistId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('serviceId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('appointmentDate', mysql.TIMESTAMP(), nullable=False))
    op.add_column('appointments', sa.Column('cancellationReason', mysql.TEXT(), nullable=True))
    op.add_column('appointments', sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_store_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_service_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'created_at')
    op.drop_column('appointments', 'appointment_time')
    op.drop_column('appointments', 'appointment_date')
    op.drop_column('appointments', 'service_id')
    op.drop_column('appointments', 'store_id')
    op.drop_column('appointments', 'user_id')
    op.create_table('favorites',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('salonId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reviews',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('salonId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('stylistId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('appointmentId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('images', mysql.JSON(), nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('openId', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=320), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('loginMethod', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('role', mysql.ENUM('user', 'admin'), server_default=sa.text("'user'"), nullable=False),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('lastSignedIn', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('users_openId_unique', 'users', ['openId'], unique=True)
    op.create_table('__drizzle_migrations',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('hash', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', '__drizzle_migrations', ['id'], unique=True)
    op.create_table('stylists',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('salonId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('avatar', mysql.TEXT(), nullable=True),
    sa.Column('bio', mysql.TEXT(), nullable=True),
    sa.Column('specialties', mysql.JSON(), nullable=True),
    sa.Column('rating', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'0'"), nullable=True),
    sa.Column('reviewCount', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('portfolio', mysql.JSON(), nullable=True),
    sa.Column('yearsOfExperience', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('isActive', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('salons',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('zipCode', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitude', mysql.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=320), nullable=True),
    sa.Column('rating', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'0'"), nullable=True),
    sa.Column('reviewCount', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('images', mysql.JSON(), nullable=True),
    sa.Column('coverImage', mysql.TEXT(), nullable=True),
    sa.Column('businessHours', mysql.JSON(), nullable=True),
    sa.Column('amenities', mysql.JSON(), nullable=True),
    sa.Column('isActive', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_verification_codes_phone'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_id'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_city'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_store_images_store_id'), table_name='store_images')
    op.drop_index(op.f('ix_store_images_id'), table_name='store_images')
    op.drop_table('store_images')
    # ### end Alembic commands ###
